package com.gtocore.common.machine.mana.multiblock;

import com.gtocore.api.machine.part.GTOPartAbility;
import com.gtocore.common.data.GTOBlocks;

import com.gtolib.api.data.GTODimensions;
import com.gtolib.utils.RegistriesUtils;

import com.gregtechceu.gtceu.api.blockentity.MetaMachineBlockEntity;
import com.gregtechceu.gtceu.api.machine.MultiblockMachineDefinition;
import com.gregtechceu.gtceu.api.pattern.BlockPattern;
import com.gregtechceu.gtceu.api.pattern.FactoryBlockPattern;
import com.gregtechceu.gtceu.api.pattern.util.RelativeDirection;

import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.Blocks;

import it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap;

import java.util.function.Supplier;

import static com.gregtechceu.gtceu.api.machine.multiblock.PartAbility.*;
import static com.gregtechceu.gtceu.api.pattern.Predicates.*;

public final class ManaCondenserMachine extends ManaMultiblockMachine {

    private static final Int2ObjectOpenHashMap<BlockPattern> PATTERNS = new Int2ObjectOpenHashMap<>(3, 0.9F);

    private int tier;

    public ManaCondenserMachine(MetaMachineBlockEntity holder) {
        super(holder);
    }

    @Override
    public void onLoad() {
        super.onLoad();
        Level level = getLevel();
        if (level == null) return;
        tier = level.dimension() == GTODimensions.ALFHEIM ? 1 : 0;
    }

    public static BlockPattern getBlockPattern(int tier, MultiblockMachineDefinition definition) {
        return PATTERNS.computeIfAbsent(tier, t -> {
            FactoryBlockPattern builder = FactoryBlockPattern.start(definition, RelativeDirection.BACK, RelativeDirection.UP, RelativeDirection.LEFT).where(' ', any());
            if (t == 0) {
                return builder.aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "       A       ", "       D       ", "       D       ", "       D       ", "       D       ", "       D       ", "       A       ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ")
                        .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "         A     ", "         D     ", "     A   D     ", "     D   D     ", "     D   D     ", "     D   D     ", "     DDDDD     ", "     A   A     ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ")
                        .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "     DAAAD     ", "      NNN      ", "      NNN      ", "      NNN      ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ")
                        .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "          A    ", "          D    ", "          D    ", "          D    ", "          D    ", "    A     D    ", "    D     D    ", "    D     D    ", "    DDAAADD    ", "    A NCN A    ", "      O N      ", "      NNN      ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ")
                        .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "     DAAAD     ", "      NNN      ", "      NNN      ", "      NNN      ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ")
                        .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "         A     ", "         D     ", "         D     ", "         D     ", "         D     ", "         D     ", "         D     ", "     A   D     ", "     D   D     ", "     DDDDD     ", "     A   A     ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ")
                        .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "       A       ", "       D       ", "       D       ", "       D       ", "       D       ", "       D       ", "       D       ", "       D       ", "       D       ", "       D       ", "       D       ", "      ADA      ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ")
                        .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "      ADA      ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ")
                        .aisle("       B       ", "       A       ", "       C       ", "       C       ", "       C       ", "       C       ", "       C       ", "       C       ", "       C       ", "       C       ", "       C       ", "       C       ", "       C       ", "       C       ", "       C       ", "       C       ", "       C       ", "       C       ", "       C       ", "    AACDCAA    ", "      C C      ", "      C C      ", "      C C      ", "      C C      ", "      C C      ", "      C C      ", "      C C      ", "      C C      ", "      C C      ", "      C C      ", "      C C      ", "      C C      ", "      C C      ", "      C C      ", "      C C      ", "      C C      ", "      C C      ", "      C A      ", "      C        ", "      A        ", "               ", "               ", "               ", "               ")
                        .aisle("               ", "               ", "         B     ", "         A     ", "         C     ", "         C     ", "         C     ", "         C     ", "         C     ", "         C     ", "         C     ", "         C     ", "         C     ", "         C     ", "         C     ", "         C     ", "         C     ", "         C     ", "         C     ", "   ACCDDDCCA   ", "          C    ", "          C    ", "          C    ", "          C    ", "          C    ", "          C    ", "          C    ", "          C    ", "          C    ", "          C    ", "          C    ", "          C    ", "          C    ", "          C    ", "          C    ", "          A    ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ")
                        .aisle("               ", "               ", "               ", "               ", "           B   ", "           A   ", "           C   ", "           C   ", "           C   ", "           C   ", "           C   ", "           C   ", "           C   ", "           C   ", "      E    C   ", "      A E  C   ", "      D A  C   ", "      D D  C   ", "      D D  C   ", "  ACDDDDDDDCA  ", "      D D      ", "      D D      ", "      D D      ", "      D D      ", "      D D      ", "      D D      ", "      DCD      ", "      A A      ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ")
                        .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "    E          ", "    A          ", "    D          ", "    D          ", "    D          ", "    D          ", " ACDDDDDDDDDCA ", "    D  F  D C  ", "    D     D C  ", "    D     D C  ", "    D     D C  ", "    D     D C  ", "    D AAA D C  ", "    DCCCCCD C  ", "    A     A C  ", "            C  ", "            C  ", "            C  ", "            C  ", "            C  ", "            A  ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ")
                        .aisle("               ", "               ", "               ", "               ", "               ", "               ", "            B  ", "            A  ", "            C  ", "            C  ", "            C  ", "            C  ", "            C  ", "            C  ", "            C  ", "            C  ", "            C  ", "            C  ", "            C  ", " ACDDDDGDDDDCA ", "     F   F     ", "               ", "               ", "               ", "               ", "     A   A     ", "    CCHHHCC    ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ")
                        .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "   E           ", "   A   A       ", "   D   A       ", "   D   A       ", "   D           ", "   D           ", "   D  G G      ", "ACDDDDGHGDDDDCA", "   D       D C ", "   D       D C ", "   D       D C ", "   D       D C ", "   D       D C ", "   DA     AD C ", "   DCHCCCHCD C ", "   D  IJI  D C ", "   D       D C ", "   A       D C ", "           D C ", "           D A ", "           D   ", "           D   ", "           D   ", "           D   ", "           D   ", "           D   ", "           D   ", "           D   ", "           D   ", "           D   ", "           D   ", "           A   ")
                        .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "             B ", "             A ", "             C ", "             C ", "       A     C ", "      A A    C ", "      AKA    C ", "      A A    C ", "       A     C ", "             C ", "             C ", "ACDDDGHHHGDDDCA", "    F  L  F    ", "               ", "               ", "               ", "               ", "    A     A    ", "   CCHCCCHCC   ", "      JJJ      ", "       M       ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ")
                        .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "   E           ", "   A           ", "   D   A       ", "   D   A       ", "   D   A       ", "   D           ", "   D           ", "   D  G G      ", "ACDDDDGHGDDDDCA", "   D       D C ", "   D       D C ", "   D       D C ", "   D       D C ", "   D       D C ", "   DA     AD C ", "   DCHCCCHCD C ", "   D  IJI  D C ", "   D       D C ", "   D       D A ", "   D       D   ", "   A       D   ", "           D   ", "           D   ", "           D   ", "           D   ", "           D   ", "           D   ", "           D   ", "           D   ", "           D   ", "           A   ", "               ", "               ")
                        .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "            B  ", "            A  ", "            C  ", "            C  ", "            C  ", "            C  ", "            C  ", "            C  ", "            C  ", " ACDDDDGDDDDCA ", "     F   F     ", "               ", "               ", "               ", "               ", "     A   A     ", "    CCHHHCC    ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ")
                        .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "    E          ", "    A          ", "    D          ", "    D          ", "    D          ", "    D          ", "    D          ", "    D          ", "    D          ", " ACDDDDDDDDDCA ", "    D  F  D C  ", "    D     D C  ", "    D     D C  ", "    D     D C  ", "    D     D C  ", "    D AAA D C  ", "    DCCCCCD C  ", "    D     D A  ", "    D     D    ", "    D     D    ", "    D     D    ", "    D     D    ", "    D     D    ", "    A     D    ", "          D    ", "          D    ", "          D    ", "          D    ", "          D    ", "          A    ", "               ", "               ", "               ", "               ")
                        .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "        E      ", "      E A      ", "      A D      ", "      D D      ", "      D D  B   ", "      D D  A   ", "      D D  C   ", "      D D  C   ", "      D D  C   ", "      D D  C   ", "      D D  C   ", "  ACDDDDDDDCA  ", "      D D      ", "      D D      ", "      D D      ", "      D D      ", "      D D      ", "      D D      ", "      DCD      ", "      D D      ", "      D D      ", "      D D      ", "      D D      ", "      D D      ", "      D D      ", "      D D      ", "      D D      ", "      A D      ", "        D      ", "        A      ", "               ", "               ", "               ", "               ", "               ", "               ")
                        .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "         B     ", "         A     ", "         C     ", "         C     ", "         C     ", "   ACCDDDCCA   ", "          C    ", "          C    ", "          C    ", "          C    ", "          C    ", "          A    ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ")
                        .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "       B       ", "       A       ", "       C       ", "    AACCCA     ", "      C C      ", "      A C      ", "        C      ", "        A      ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ")
                        .aisle("               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "      AAA      ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ", "               ")
                        .where('A', blocks(RegistriesUtils.getBlock("botania:elf_glass")))
                        .where('B', blocks(RegistriesUtils.getBlock("botania:natura_pylon")))
                        .where('C', blocks(GTOBlocks.MANASTEEL_CASING.get()))
                        .where('D', blocks(GTOBlocks.ELEMENTIUM_CASING.get()))
                        .where('E', blocks(RegistriesUtils.getBlock("botania:mana_pylon")))
                        .where('F', blocks(RegistriesUtils.getBlock("botania:apothecary_livingrock")))
                        .where('G', blocks(RegistriesUtils.getBlock("botania:glimmering_dreamwood")))
                        .where('H', blocks(RegistriesUtils.getBlock("botania:glimmering_livingwood")))
                        .where('I', blocks(Blocks.LAPIS_BLOCK))
                        .where('J', blocks(RegistriesUtils.getBlock("botania:livingrock")))
                        .where('K', blocks(RegistriesUtils.getBlock("botania:corporea_index")))
                        .where('L', blocks(RegistriesUtils.getBlock("botania:runic_altar")))
                        .where('M', blocks(RegistriesUtils.getBlock("botania:terra_plate")))
                        .where('N', blocks(GTOBlocks.MANASTEEL_CASING.get())
                                .or(abilities(GTOPartAbility.INPUT_MANA).setMaxGlobalLimited(16, 1))
                                .or(abilities(PARALLEL_HATCH).setMaxGlobalLimited(1))
                                .or(abilities(IMPORT_FLUIDS).setMaxGlobalLimited(4, 1))
                                .or(abilities(EXPORT_ITEMS).setMaxGlobalLimited(4, 1))
                                .or(abilities(IMPORT_ITEMS).setMaxGlobalLimited(4, 1)))
                        .where('O', controller(definition))
                        .build();
            } else {
                return builder.aisle("                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "            A       ", "            K       ", "            K       ", "            K       ", "            K       ", "            K       ", "            A       ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ")
                        .aisle("                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "              A     ", "              K     ", "          A   K     ", "          K   K     ", "          K   K     ", "          K   K     ", "          KKKKK     ", "          A   A     ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ")
                        .aisle("                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "          KAAAK     ", "           UUU      ", "           UUU      ", "           UUU      ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ")
                        .aisle("                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "               A    ", "               K    ", "               K    ", "               K    ", "         A     K    ", "         K     K    ", "         K     K    ", "         KKAAAKK    ", "         A UJU A    ", "           V U      ", "           UUU      ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ")
                        .aisle("                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "          KAAAK     ", "           UUU      ", "           UUU      ", "           UUU      ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ")
                        .aisle("                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "              A     ", "              K     ", "              K     ", "              K     ", "              K     ", "              K     ", "          A   K     ", "          K   K     ", "          KKKKK     ", "          A   A     ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ")
                        .aisle("                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "            A       ", "            K       ", "            K       ", "            K       ", "            K       ", "            K       ", "            K       ", "            K       ", "            K       ", "           AKA      ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ")
                        .aisle("                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "           AKA      ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ")
                        .aisle("            I       ", "            A       ", "            J       ", "            J       ", "            J       ", "            J       ", "            J       ", "            J       ", "            J       ", "            J       ", "            J       ", "            J       ", "            J       ", "            J       ", "            J       ", "            J       ", "            J       ", "            J       ", "            J       ", "         AAJKJAA    ", "           J J      ", "           J J      ", "           J J      ", "           J J      ", "           J J      ", "           J J      ", "           J J      ", "           J J      ", "           J J      ", "           J J      ", "           J J      ", "           J J      ", "           J J      ", "           J J      ", "           J J      ", "           J J      ", "           J J      ", "           J A      ", "           J        ", "           A        ", "                    ", "                    ", "                    ", "                    ")
                        .aisle("                    ", "                    ", "              I     ", "              A     ", "              J     ", "              J     ", "              J     ", "              J     ", "              J     ", "              J     ", "              J     ", "              J     ", "              J     ", "              J     ", "              J     ", "              J     ", "              J     ", "              J     ", "              J     ", "        AJJKKKJJA   ", "               J    ", "               J    ", "               J    ", "               J    ", "               J    ", "               J    ", "               J    ", "               J    ", "               J    ", "               J    ", "               J    ", "               J    ", "               J    ", "               J    ", "               J    ", "               A    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ")
                        .aisle("                    ", "                    ", "                    ", "                    ", "                I   ", "                A   ", "                J   ", "                J   ", "                J   ", "                J   ", "                J   ", "                J   ", "                J   ", "                J   ", "           L    J   ", "           A L  J   ", "           K A  J   ", "           K K  J   ", "           K K  J   ", "       AJKKKKKKKJA  ", "           K K      ", "           K K      ", "           K K      ", "           K K      ", "           K K      ", "           K K      ", "           KJK      ", "           A A      ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ")
                        .aisle("                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "         L          ", "         A          ", "         K          ", "         K          ", "         K          ", "         K          ", "      AJKKKKKKKKKJA ", "         K  M  K J  ", "         K     K J  ", "         K     K J  ", "         K     K J  ", "         K     K J  ", "         K AAA K J  ", "         KJJJJJK J  ", "         A     A J  ", "                 J  ", "                 J  ", "                 J  ", "                 J  ", "                 J  ", "                 A  ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ")
                        .aisle("                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                 I  ", "                 A  ", "                 J  ", "                 J  ", "                 J  ", "                 J  ", "                 J  ", "                 J  ", "                 J  ", "                 J  ", "                 J  ", "                 J  ", "                 J  ", "      AJKKKKNKKKKJA ", "          M   M     ", "                    ", "                    ", "                    ", "                    ", "          A   A     ", "         JJOOOJJ    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ")
                        .aisle("                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "        L           ", "        A   A       ", "        K   A       ", "        K   A       ", "        K           ", "        K           ", "        K  N N      ", "     AJKKKKNONKKKKJA", "        K       K J ", "        K       K J ", "        K       K J ", "        K       K J ", "        K       K J ", "        KA     AK J ", "        KJOJJJOJK J ", "        K  PQP  K J ", "        K       K J ", "        A       K J ", "                K J ", "                K A ", "                K   ", "                K   ", "                K   ", "                K   ", "                K   ", "                K   ", "                K   ", "                K   ", "                K   ", "                K   ", "                K   ", "                A   ")
                        .aisle("                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                  I ", "                  A ", "                  J ", "                  J ", "            A     J ", "           A A    J ", "           ARA    J ", "           A A    J ", "            A     J ", "                  J ", "                  J ", "     AJKKKNOOONKKKJA", "         M  S  M    ", "                    ", "                    ", "                    ", "                    ", "         A     A    ", "        JJOJJJOJJ   ", "           QQQ      ", "            T       ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ")
                        .aisle("                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "        L           ", "        A           ", "        K   A       ", "        K   A       ", "        K   A       ", "        K           ", "        K           ", "        K  N N      ", "     AJKKKDNONKKKKJA", "        K       K J ", "        K       K J ", "        K       K J ", "        K       K J ", "        K       K J ", "        KA     AK J ", "        KJOJJJOJK J ", "        K  PQP  K J ", "        K       K J ", "        K       K A ", "        K       K   ", "        A       K   ", "                K   ", "                K   ", "                K   ", "                K   ", "                K   ", "                K   ", "                K   ", "                K   ", "                K   ", "                A   ", "                    ", "                    ")
                        .aisle("                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                 I  ", "                 A  ", "                 J  ", "                 J  ", "                 J  ", "                 J  ", "                 J  ", "                 J  ", "                 J  ", "      AJKDDDNKKKKJA ", "          M   M     ", "                    ", "                    ", "                    ", "                    ", "          A   A     ", "         JJOOOJJ    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ")
                        .aisle("                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "         L          ", "         A          ", "         K          ", "         K          ", "         K          ", "         K          ", "         K          ", "         K          ", "         K          ", "      AJDDDKKKKKKJA ", "         K  M  K J  ", "         K     K J  ", "         K     K J  ", "         K     K J  ", "         K     K J  ", "         K AAA K J  ", "         KJJJJJK J  ", "         K     K A  ", "         K     K    ", "         K     K    ", "         K     K    ", "         K     K    ", "         K     K    ", "         A     K    ", "               K    ", "               K    ", "               K    ", "               K    ", "               K    ", "               A    ", "                    ", "                    ", "                    ", "                    ")
                        .aisle("                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "             L      ", "           L A      ", "           A K      ", "           K K      ", "           K K  I   ", "           K K  A   ", "           K K  J   ", "           K K  J   ", "           K K  J   ", "           K K  J   ", "           K K  J   ", "    AAADDDKKKKKKJA  ", "           K K      ", "           K K      ", "           K K      ", "           K K      ", "           K K      ", "           K K      ", "           KJK      ", "           K K      ", "           K K      ", "           K K      ", "           K K      ", "           K K      ", "           K K      ", "           K K      ", "           K K      ", "           A K      ", "             K      ", "             A      ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ")
                        .aisle("                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "              I     ", "              A     ", "    B         J     ", "    C         J     ", "    D         J     ", "  AADADDDJJKKKJJA   ", "    D          J    ", "    D          J    ", "    D          J    ", "    D          J    ", "    D          J    ", "    D          A    ", "    D               ", "    D               ", "    D               ", "    D               ", "    D               ", "    D               ", "    D               ", "    D               ", "    C               ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ")
                        .aisle("                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "  B                 ", "  C                 ", "  D         I       ", "  D         A       ", "  D         J       ", " ADDDDDDAAAJJJA     ", "  D        J J      ", "  D        A J      ", "  D          J      ", "  D          A      ", "  D                 ", "  D                 ", "  D                 ", "  D                 ", "  D                 ", "  D                 ", "  D                 ", "  D                 ", "  C                 ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ")
                        .aisle("                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "    C               ", "                    ", "                    ", "                    ", " ADDDDDAA  AAA      ", "   EFE              ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ")
                        .aisle("                    ", "                    ", "                    ", "                    ", "       B            ", "       C            ", "       D            ", "       D            ", "       D            ", "       D            ", "       D            ", "       D            ", " B     D            ", " C     D            ", " D  C  D            ", " D CGC D            ", " D  C  D            ", " D     D            ", " D     D            ", "ADDDCDDDA           ", " D FEF D            ", " D  H  D            ", " D     C            ", " D                  ", " D                  ", " D                  ", " D                  ", " D                  ", " D                  ", " D                  ", " C                  ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ")
                        .aisle("                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "    C               ", "                    ", "                    ", "                    ", " ADDDDDA            ", "   EFE              ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ")
                        .aisle("                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "      B             ", "      C             ", "      D             ", "      D             ", "  B   D             ", "  C   D             ", "  D   D             ", "  D   D             ", "  D   D             ", "  D   D             ", "  D   D             ", "  D   D             ", "  D   D             ", " ADDDDDA            ", "  D   D             ", "  D   D             ", "  D   D             ", "  D   D             ", "  D   C             ", "  D                 ", "  D                 ", "  D                 ", "  C                 ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ")
                        .aisle("                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "    B               ", "    C               ", "    D               ", "    D               ", "    D               ", "    D               ", "    D               ", "    D               ", "    D               ", "    D               ", "    D               ", "  AADAA             ", "    D               ", "    D               ", "    D               ", "    D               ", "    D               ", "    D               ", "    C               ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ")
                        .aisle("                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "    A               ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ", "                    ")
                        .where('A', blocks(RegistriesUtils.getBlock("botania:elf_glass")))
                        .where('B', blocks(RegistriesUtils.getBlock("mythicbotany:alfsteel_pylon")))
                        .where('C', blocks(RegistriesUtils.getBlock("botania:bifrost_perm")))
                        .where('D', blocks(GTOBlocks.GAIASTEEL_CASING.get()))
                        .where('E', blocks(RegistriesUtils.getBlock("botania:shimmerrock")))
                        .where('F', blocks(Blocks.GOLD_BLOCK))
                        .where('G', blocks(RegistriesUtils.getBlock("mythicbotany:alfsteel_block")))
                        .where('H', blocks(RegistriesUtils.getBlock("mythicbotany:mana_infuser")))
                        .where('I', blocks(RegistriesUtils.getBlock("botania:natura_pylon")))
                        .where('J', blocks(GTOBlocks.MANASTEEL_CASING.get()))
                        .where('K', blocks(GTOBlocks.ELEMENTIUM_CASING.get()))
                        .where('L', blocks(RegistriesUtils.getBlock("botania:mana_pylon")))
                        .where('M', blocks(RegistriesUtils.getBlock("botania:apothecary_livingrock")))
                        .where('N', blocks(RegistriesUtils.getBlock("botania:glimmering_dreamwood")))
                        .where('O', blocks(RegistriesUtils.getBlock("botania:glimmering_livingwood")))
                        .where('P', blocks(Blocks.LAPIS_BLOCK))
                        .where('Q', blocks(RegistriesUtils.getBlock("botania:livingrock")))
                        .where('R', blocks(RegistriesUtils.getBlock("botania:corporea_index")))
                        .where('S', blocks(RegistriesUtils.getBlock("botania:runic_altar")))
                        .where('T', blocks(RegistriesUtils.getBlock("botania:terra_plate")))
                        .where('U', blocks(GTOBlocks.MANASTEEL_CASING.get())
                                .or(abilities(GTOPartAbility.INPUT_MANA).setMaxGlobalLimited(32, 1))
                                .or(abilities(PARALLEL_HATCH).setMaxGlobalLimited(1))
                                .or(abilities(IMPORT_FLUIDS).setMaxGlobalLimited(4, 1))
                                .or(abilities(EXPORT_ITEMS).setMaxGlobalLimited(4, 1))
                                .or(abilities(IMPORT_ITEMS).setMaxGlobalLimited(4, 1)))
                        .where('V', controller(definition))
                        .where(' ', any())
                        .build();
            }
        });
    }

    @Override
    public Supplier<BlockPattern>[] getPattern() {
        return new Supplier[] { () -> getBlockPattern(tier, getDefinition()) };
    }
}
